secret:
  ignored_matches:
  - match: '*.env.example'
    name: Environment template files
  ignored_paths:
  - '*.pyc'
  - '**/node_modules/**'
  - .venv/**
  - '*.log'
  - '**/__pycache__/**'
  - '*.md'
  - .git/**
version: 2
