services:
  # Main web service for the full-stack application
  - type: web
    name: coachwilltumbles
    runtime: node
    env: node
    plan: starter
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: coachwilltumbles-db
          property: connectionString
      # These will need to be set manually in Render dashboard:
      # - SUPABASE_URL
      # - SUPABASE_ANON_KEY  
      # - SUPABASE_SERVICE_ROLE_KEY
      # - STRIPE_SECRET_KEY
      # - STRIPE_WEBHOOK_SECRET
      # - RESEND_API_KEY
      # - SESSION_SECRET
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      # - BASE_URL (set to your Render app URL)

databases:
  # PostgreSQL database for the application
  - name: coachwilltumbles-db
    databaseName: coachwilltumbles
    user: coachwill
    plan: starter
